### PR TITLE
Feature/run migrations

### LINKED ISSUE #41: Getting error of Missing required parameters: siteHandle

### PR DESCRIPTION
**Pull request by niektenhoopen**
This fixes #41 #42 #43 and #44

### CODE REVIEW

**Comment by niektenhoopen** [comment]
I am not sure if this fixes all issues that were created in 1.1.7 but at least some of them. I think you are probably able to tell if there are more.

**Comment by alinistrate** [comment]
Hi @niektenhoopen 
Can you please pull the latest version now and do the fixes? There are some conflicts with what I did and I cannot pull the changes.

**Comment by niektenhoopen** [comment]
@alinistrate I see you also started fixing the issues. Feel free to use any of the above. I think I improved some bits (the migrations and getting the current site handle in the Controller if none is set so that the current URL without siteHandle keeps working). Open to discussion

**Comment by alinistrate** [comment]
@niektenhoopen 
Thank you! Please do another pull request. I will review and merge. Also bump the version to 1.1.10


Thanks,
Alin

**Comment by niektenhoopen** [comment]
Ok, will make another change for the bump

**Comment by alinistrate** [comment]
@niektenhoopen 
Thank you. Really glad that people are using the plugin and it's useful. Initially, we developed the plugin for our internal use. 

The help contributing to this is much appreciated.

Thanks,
Alin

**Pull request merged**
